repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: local
    hooks:
    -   id: mypy
        name: mypy
        entry: mypy --config-file mypy.ini
        exclude: migrations/
        language: system
        types: [python]
    -   id: pytest
        name: pytest
        pass_filenames: false
        entry: pytest
        exclude: migrations/
        language: system
        types: [python]
    -   id: flake8
        name: flake8
        entry: flake8 app
        exclude: migrations/
        language: system
        types: [python]
